name: cpsl_flutter
description: "A demo app for using Capsule SDK in Flutter"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  capsule:
    path: "../../../flutter-sdk"
  flutter_dotenv: ^5.2.1
  flutter_inappwebview: ^6.1.5
  font_awesome_flutter: ^10.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
