name: cpsl_flutter
description: "A demo app for using Capsule SDK in Flutter"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  capsule_phantom_connector: ^0.0.1
  capsule_metamask_connector: ^0.0.1
  flutter_dotenv: ^5.2.1
  flutter_inappwebview: ^6.1.5
  font_awesome_flutter: ^10.8.0
  web3dart: ^2.7.3
  solana_web3: ^0.1.3
  flutter_svg: ^2.0.16
  reown_appkit: ^1.3.0
  reown_walletkit: ^1.1.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
dependency_overrides:
  pinenacl: 0.6.0
  web_socket_channel: ^3.0.1
  js: ^0.7.1

flutter:
  uses-material-design: true
  assets:
    - .env
    - lib/assets/farcaster.svg
